### PR TITLE
Switch main tags over to python:slim

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
See https://botbot.me/freenode/docker-library/msg/32141718/ for context.

**Comment by tianon** [comment]
This one needs more love.

**Comment by tianon** [comment]
Updated, but I'm on kind of crappy WiFi right now so the full `python` variants are taking a while to download for me to build-test the `onbuild` variant changes.

**Comment by tianon** [comment]
```console
$ ./generate-stackbrew-library.sh | sed 's/docker-library/infosiftr/' > django
$ bashbrew build ./django
Fetching django (git://github.com/infosiftr/django) ...
Processing django:1.7.4-python2 ...
Processing django:1.7-python2 ...
Processing django:1-python2 ...
Processing django:python2 ...
Processing django:python2-onbuild ...
Processing django:1.7.4-python3 ...
Processing django:1.7.4 ...
Processing django:1.7-python3 ...
Processing django:1.7 ...
Processing django:1-python3 ...
Processing django:1 ...
Processing django:python3 ...
Processing django:latest ...
Processing django:python3-onbuild ...
Processing django:onbuild ...
```

**Comment by yosifkit** [comment]
LGTM

**Pull request merged**
