### PR TITLE
Base Django images out of Alpine 3.3

### PR DESCRIPTION
**Pull request by rvernica**
I made the necessary changes to base the Django images out of Alpine 3.3.

Here are a few notes:
1. The required database libraries for SQLite, MySQL and PostgreSQL are installed first.
2. `pip install` requires some `-dev` packages. I install the `-dev` packages, run `pip` and then remove the `-dev` packages. (I use the `apk`'s `virtual` feature.) All this is done in a single Docker command. This keeps the images small. This is also done for `onbuild` images when the `requirements.txt` are installed.
3. For the Python 3 image, Alpine 3.3 comes with Python 3.5, so I changed the directory name from `3.4` to `3.5` and updated the Travis configuration file.
4. I tested the four images (2.7, 2.7-onbuild, 3.5, and 3.5-onbuild) by running a small project with Django Admin interface on SQLite, MySQL (MariaDB) and PostgreSQL back-ends.

### CODE REVIEW

**Comment by rvernica** [comment]
Build failed due to DNS issues with Alpine Linux. Their domain expired briefly and was re-registered shortly after. The [build on my fork](https://travis-ci.org/rvernica/django/builds/117752129) was successful.

**Comment by rvernica** [comment]
I built the images in [my Docker Hub](https://hub.docker.com/r/rvernica/django/tags/) and their reported size is `18-37MB`. Compare that to `158-280MB` for the [non-Alpine images](https://hub.docker.com/r/library/django/tags/).

**Comment by mwaaas** [comment]
would love to see this changes merged

**Comment by yosifkit** [comment]
We have deprecated the django image in favor of just the python image: https://github.com/docker-library/docs/pull/630.

**Pull request closed without merging**
